### ISSUE TITLE
Создание алгоритма перемешивания фишек

### ISSUE THREAD

**Issue by SainTool** [trpo2021/cw-ip-015_game_15_puzzle#8]
Изначально собранное поле компьютер сам перемешивает совершая те же действия что и игрок. В результате головоломку будет возможно решить. Действия компьютер должен совершать случайно.

**Comment by SainTool** [comment]
+ исключить повторение действий компьютером (если он начнёт перетаскивать одну и ту же фишку, к примеру вверх вниз)

**Comment by Jamesss1337** [comment]
Изначально собранное поле пятнашек перемешивается случайно. Далее проходит проверка на "четность расклада" т.е так называемый параметр беспорядка (число пар чисел, в которых большее число предшествует меньшему с прибавлением номера горизонтального ряда с пустой клеткой), должен быть четный.
